config/routes.rb
Hackathon::Application.routes.draw do
  root to: 'main#index'
  get '/login', to: 'main#login', as: "login"
  get '/demo', to: 'demo#new', as: "demo"
  post '/demo', to: 'demo#create', as: "demo"
  get '/success', to: 'demo#success', as: "demo_success"
  get '/failure', to: 'demo#failure', as: "demo_success"
end

app/models/operator.rb
class Operator < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/demo_controller.rb
class DemoController < ApplicationController

  def new
  end

  def create
    result = `cd ./lib/ML && python3.6 #{Rails.root}/lib/ML/Hackana_beta.py "#{params[:carater_atendimento]};#{params[:service_id]};#{params[:sexo]};#{params[:item_kind]};#{params[:charged_value]};#{params[:days_inside]};#{params[:years_old]}"`
    result.gsub!("\n","")
    if result == "1"
      redirect_to action: :failure and return    
    else
      redirect_to action: :success and return    
    end
  end

  def failure
  end

  def success
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def login
  end

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/demo/failure.html.erb
<%= content_for :head do %>
  <style>
    .all{
      position: absolute;
      margin: 0 auto;
      width: 60%;
      height: 60%;
      background-image: url("<%=image_path 'not_ok.png'%>");
      background-size: contain;
      background-repeat: no-repeat;
    }
  </style>
<% end %>
<div class="text-center" style="margin-top:  50px;">
  <div class="container"><h1>Faturamento não Aprovado!</h1></div>
  <div class="container all" style="margin-left: 474px;">
  </div>
</div>

app/views/demo/new.html.erb
<% content_for :head do %>
  <style>
    .request-form{
      margin: 0 auto;
      width: 60%;
    }
    .margin-top{
      margin-top: 15px;
    }
    .full-margin-top{
      margin-top: 50px;
    }
  </style>
<% end %>
<div class="container text-center full-margin-top">
  <div class="container">
    <h1>Demonstração</h1>
  </div>

  <div class="form">
      <div class="request-form text-left">
        <hr/>
        </div>
        <form class="request-form" method="post" action="<%= demo_path%>">
      <div class="row">
        <div class="col">
          <div class="text-left">
            <label class="label-default">Carater atendimento</label>
          </div>
          <%= select_tag "carater_atendimento", options_for_select(['ELETIVO', 'URGENCIA']), class: "custom-select"%>
        </div>
        <div class="col">
          <div class="text-left">
            <label class="label-default">Serviço</label>
          </div>
          <input type="text" class="form-control" name="service_id" placeholder="Digite o id">
        </div>
      </div>
      <div class="row margin-top">
        <div class="col">
          <div class="text-left">
            <label class="label-default">Sexo:</label>
          </div>
          <%= select_tag "sexo", options_for_select([['Masculino',"M"],["Feminino", "F"]]), class: "custom-select"%>
        </div>
        <div class="col">
          <div class="text-left">
            <label class="label-default">Tipo do item:</label>
          </div>
          <%= select_tag "item_kind", options_for_select(['DIARIAS', 'GASES MEDICINAIS', 'MATERIAIS', 'MEDICAMENTOS', 'OPME','PROCEDIMENTO', 'TAXAS DIVERSAS']), class: "custom-select"%>
        </div>
        <div class="col">
          <div class="text-left">
            <label class="label-default">Valor Cobrado:</label>
          </div>
          <input type="text" class="form-control" name="charged_value">
        </div>
      </div>
      <div class="row">
        <div class="col">
          <div class="text-left">
            <label class="label-default">Dias em tratamento:</label>
          </div>
          <input type="text" class="form-control" name="days_inside">
        </div>
        <div class="col">
          <div class="text-left">
            <label class="label-default">Idade:</label>
          </div>
          <input type="text" class="form-control" name="years_old">
        </div>
      </div>
      <div class="row margin-top">
        <div class="col text-right">
          <button type="submit" class="btn btn-primary">Confirmar</button>
        </div>
      </div>
    </form>
  </div>
</div>

app/views/demo/success.html.erb
<%= content_for :head do %>
  <style>
    .all{
      position: absolute;
      margin: 0 auto;
      width: 60%;
      height: 60%;
      background-image: url("<%=image_path 'ok.png'%>");
      background-size: contain;
      background-repeat: no-repeat;
    }
  </style>
<% end %>
<div class="text-center" style="margin-top:  50px;">
  <div class="container"><h1>Faturamento Aprovado!</h1></div>
  <div class="container all" style="margin-left: 500px;">
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hackathon</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  <%= csrf_meta_tags %>
  <style>
    body{
      background-color: #f1f1f1;
    }
  </style>
  <%= yield :head %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/main/index.html.erb
<%content_for :head do %>
  <style>
    .all{
      background-image: url("<%=image_path 'background-index.jpg'%>");
      position: absolute;
      width: 100%;
      height: 100%;
      background-position: center;
      background-size: cover;
    }
    .main-content{
      width: 60%;
      margin: 50px auto;
    }
    
  </style>
<% end %>

<div class="all">
  <div class="main-content vertical-center text-center">
    <h1>Dra. Ana</h1>
  </div>
  <div class="main-content">
    <div class="row">
      <div class="col-sm-6 text-right">
        <%= link_to "Demo", login_path, class: "btn btn-info"%>
      </div>
      <div class="col-sm-6">
        <%= link_to "login", login_path, class: "btn btn-info"%>
      </div>
    </div>
  </div>
</div>

app/views/main/login.html.erb
% content_for :head do %>
  <style>
    .margin-top{
      margin-top: 50px;
    }
    
    .form-container{
      margin: 0 auto;
      width: 50%;
    }
  </style>
<% end %>
<div class="vertical-center text-center margin-top">
  <div class="container">
    <h1>Medico Analísta 2.0</h1>
  </div>
  <div class="container">
    <form class="form-container">
      <div class="form-group">
        <label for="email">Email</label>
        <input type="email" class="form-control" id="email" aria-describedby="emailHelp" placeholder="Digite o email">
        <small id="emailHelp" class="form-text text-muted">Digite o email que você utilizou no seu cadastro.</small>
      </div>
      <div class="form-group">
        <label for="exampleInputPassword1">Password</label>
        <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
      </div>
      <button type="submit" class="btn btn-primary">Submit</button>
      <%=link_to ""%>
    </form>
  </div>
</div>